<div>
    <script
        src="https://giscus.app/client.js"
        data-repo="Neulhan/Neulhan"
        data-repo-id="MDEwOlJlcG9zaXRvcnkyODc0NzE2OTA="
        data-category="Announcements"
        data-category-id="DIC_kwDOESJ4Ss4CeXnk"
        data-mapping="title"
        data-strict="0"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="top"
        data-theme="light"
        data-lang="ko"
        data-loading="lazy"
        crossorigin="anonymous"
        async>
    </script>
</div>
